language: node_js

node_js:
  - node

addons:
  apt:
    packages:
      - libgconf-2-4

cache:
  npm: true
  directories:
    # We also need to cache folder with Cypress binary.
    - ~/.cache

before_install:
  - pip install --user awscli
  - export PATH=$PATH:$HOME/.local/bin

install: npm install

script:
  - npm test
  - npx start-server-and-test start http://localhost:3000 cy:run
  - npm run build

deploy:
  provider: script
  skip_cleanup: true
  script: ./scripts/deploy.sh
  on:
    branch: master
